// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// make_blocks_cpp
List make_blocks_cpp(NumericVector ld_lookup_r, DataFrame ld_adj_r, CharacterVector marker_names_r, IntegerVector marker_idx_r, LogicalVector assigned_r, std::string method, double threshold, int tolerance, bool tol_reset, std::string start);
RcppExport SEXP _FastStack_make_blocks_cpp(SEXP ld_lookup_rSEXP, SEXP ld_adj_rSEXP, SEXP marker_names_rSEXP, SEXP marker_idx_rSEXP, SEXP assigned_rSEXP, SEXP methodSEXP, SEXP thresholdSEXP, SEXP toleranceSEXP, SEXP tol_resetSEXP, SEXP startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ld_lookup_r(ld_lookup_rSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type ld_adj_r(ld_adj_rSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type marker_names_r(marker_names_rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type marker_idx_r(marker_idx_rSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type assigned_r(assigned_rSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< bool >::type tol_reset(tol_resetSEXP);
    Rcpp::traits::input_parameter< std::string >::type start(startSEXP);
    rcpp_result_gen = Rcpp::wrap(make_blocks_cpp(ld_lookup_r, ld_adj_r, marker_names_r, marker_idx_r, assigned_r, method, threshold, tolerance, tol_reset, start));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FastStack_make_blocks_cpp", (DL_FUNC) &_FastStack_make_blocks_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_FastStack(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
