# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' compute_local_ld_edges_cpp
#'
#' Windowed pairwise r^2 over one chromosome. geno is sample by marker; snps and
#' pos follow the same column order. For marker i only i+1, ..., i+W_snp are
#' evaluated, and only pairs reaching min_r2 are returned, with indices converted
#' back to 1-based R positions. See local_ld_edges in R/blocking_graph.R.
compute_local_ld_edges_cpp <- function(geno, snps, pos, W_snp, min_r2) {
    .Call(`_HapSelect_compute_local_ld_edges_cpp`, geno, snps, pos, W_snp, min_r2)
}

#' has_strong_ld_to_block_cpp
#'
#' Whether a target marker reaches threshold r^2 against any one member of a
#' block, recomputed from the genotypes rather than read from the edge table, so
#' neither the LD window nor the edge-table floor constrains it. Returns as soon
#' as a member qualifies. See block_ld_support in R/blocking_graph.R.
has_strong_ld_to_block_cpp <- function(geno, target_col, member_cols, threshold) {
    .Call(`_HapSelect_has_strong_ld_to_block_cpp`, geno, target_col, member_cols, threshold)
}

#' connected_components_cpp
#'
#' Component label for every vertex of an undirected graph, by union-find with
#' path compression and union by size. Stands in for igraph's components() so
#' that the one graph operation the method needs does not pull in igraph.
#'
#' Labels are assigned in order of first appearance while walking the vertices,
#' which is not meaningful on its own: core_blocks() re-sorts each component by
#' marker index and re-orders the components by their first marker, so the
#' labelling here cannot affect the blocks that come out.
#'
#' from, to : 1-based vertex indices, one pair per edge
#' n_vertex : total vertices, including any with no edges at all
connected_components_cpp <- function(from, to, n_vertex) {
    .Call(`_HapSelect_connected_components_cpp`, from, to, n_vertex)
}

#' make_blocks_cpp
#'
#' R-facing wrapper around make_blocks. Converts R named vectors to C++ types
#' once up front, calls make_blocks, then converts the result back to R types.
#' See make_blocks in R/def_haploblocks.R for full parameter documentation.
make_blocks_cpp <- function(ld_lookup_r, ld_adj_r, marker_names_r, marker_idx_r, assigned_r, method, threshold, tolerance, tol_reset, start) {
    .Call(`_HapSelect_make_blocks_cpp`, ld_lookup_r, ld_adj_r, marker_names_r, marker_idx_r, assigned_r, method, threshold, tolerance, tol_reset, start)
}

#' pairwise_ld_cpp
#'
#' Pairwise r^2 between markers on one chromosome. Called by ld_func_c().
#'
#' geno    : samples in rows, markers in columns
#' window  : compare markers at most this many positions apart; pass the marker
#'           count for every pair
#' min_r2  : drop pairs below this r^2; pass a negative value to keep all
#' min_obs : samples that must be observed at both markers for a pair to be kept
#'
#' Returns Locus1, Locus2 (1-based marker positions) and LD. Pairs with an
#' undefined r^2 are left out.
pairwise_ld_cpp <- function(geno, window, min_r2, min_obs) {
    .Call(`_HapSelect_pairwise_ld_cpp`, geno, window, min_r2, min_obs)
}

