# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' make_blocks_cpp
#'
#' R-facing wrapper around make_blocks. Converts R named vectors to C++ types
#' once up front, calls make_blocks, then converts the result back to R types.
#' See make_blocks in R/def_haploblocks.R for full parameter documentation.
make_blocks_cpp <- function(ld_lookup_r, ld_adj_r, marker_names_r, marker_idx_r, assigned_r, method, threshold, tolerance, tol_reset, start) {
    .Call(`_HapSelect_make_blocks_cpp`, ld_lookup_r, ld_adj_r, marker_names_r, marker_idx_r, assigned_r, method, threshold, tolerance, tol_reset, start)
}

#' pairwise_ld_cpp
#'
#' Pairwise r^2 between markers on one chromosome. Called by ld_func_c().
#'
#' geno    : samples in rows, markers in columns
#' window  : compare markers at most this many positions apart; pass the marker
#'           count for every pair
#' min_r2  : drop pairs below this r^2; pass a negative value to keep all
#' min_obs : samples that must be observed at both markers for a pair to be kept
#'
#' Returns Locus1, Locus2 (1-based marker positions) and LD. Pairs with an
#' undefined r^2 are left out.
pairwise_ld_cpp <- function(geno, window, min_r2, min_obs) {
    .Call(`_HapSelect_pairwise_ld_cpp`, geno, window, min_r2, min_obs)
}

