# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' make_blocks_cpp
#'
#' R-facing wrapper around make_blocks. Converts R named vectors to C++ types
#' once up front, calls make_blocks, then converts the result back to R types.
#' See make_blocks in R/def_haploblocks.R for full parameter documentation.
make_blocks_cpp <- function(ld_lookup_r, ld_adj_r, marker_names_r, marker_idx_r, assigned_r, method, threshold, tolerance, tol_reset, start) {
    .Call(`_FastStack_make_blocks_cpp`, ld_lookup_r, ld_adj_r, marker_names_r, marker_idx_r, assigned_r, method, threshold, tolerance, tol_reset, start)
}

